// src/data/services.ts
export interface Service {
  id: string;
  title: string;
  shortDescription: string;
  longDescription: string;
  image: string;
}

export const services: Service[] = [
  {
    id: "images",
    title: "Customizable Images",
    shortDescription: "Tailored digital images for branding and campaigns.",
    longDescription: `
      We design and deliver customizable images adapted to your brand identity.
      From professional graphics to social media content, our solutions ensure
      strong visual impact and consistency.

      Examples:
      - Brand visuals
      - Marketing graphics
      - Personalized assets
    `,
    image: "/images/services/images.jpg",
  },
  {
    id: "gif",
    title: "Custom GIFs",
    shortDescription: "Eye-catching GIFs for digital marketing and community use.",
    longDescription: `
      Animated GIFs crafted to capture attention and engage communities.
      Perfect for social media campaigns, meme culture, or corporate branding.

      Examples:
      - Marketing GIFs
      - Memes and fun animations
      - Product promotions
    `,
    image: "/images/services/gif.gif",
  },
  {
    id: "vr-ar",
    title: "VR/AR Experiences",
    shortDescription: "Personalized VR/AR scenes and gamified experiences.",
    longDescription: `
      We build immersive VR and AR environments designed for relaxation,
      training, or entertainment. Engage your audience with state-of-the-art
      3D interactive experiences.

      Examples:
      - VR therapy scenes
      - Gamified product demos
      - AR filters and effects
    `,
    image: "/images/services/vrar.jpg",
  },
  {
    id: "lore",
    title: "Lore Creation",
    shortDescription: "Full story world-building for games, brands, and NFTs.",
    longDescription: `
      Narrative is power. We create engaging lore that gives depth to your brand,
      NFT collection, or game. From mythologies to story arcs, we craft immersive
      universes that resonate with your audience.

      Examples:
      - NFT backstories
      - Game world-building
      - Corporate storytelling
    `,
    image: "/images/services/lore.jpg",
  },
  {
    id: "website",
    title: "Autogenerated Websites",
    shortDescription: "Self-deployed, AI-powered professional websites.",
    longDescription: `
      Rapid website deployment with AI support. From layout generation to 
      hosting automation, we deliver modern, scalable, and SEO-friendly sites.

      Features:
      - AI-assisted design
      - Automated deployment
      - Secure and scalable hosting
    `,
    image: "/images/services/website.jpg",
  },
  {
    id: "marketing",
    title: "Marketing Campaigns",
    shortDescription: "Full-scale advertising and engagement campaigns.",
    longDescription: `
      End-to-end digital marketing campaigns that include design, ads,
      analytics, and growth hacking. We maximize visibility and ROI
      across all major platforms.

      Services:
      - Advertising campaigns
      - Growth hacking
      - Social media strategy
    `,
    image: "/images/services/marketing.jpg",
  },
  {
    id: "meme",
    title: "Memes",
    shortDescription: "Video and image memes tailored to your brand.",
    longDescription: `
      Viral and entertaining memes that align with your project’s identity.
      Our creative team blends humor with strategy for organic traction.

      Examples:
      - Meme packs
      - Trend-based content
      - Social virality boosters
    `,
    image: "/images/services/meme.jpg",
  },
  {
    id: "ghostwriting",
    title: "Ghostwriting",
    shortDescription: "Professional texts, scripts, and storytelling.",
    longDescription: `
      Ghostwriting services for companies and creators.
      From blog posts to speeches, we deliver words that engage and convert.

      Examples:
      - Blog posts and articles
      - Scripts for videos
      - Brand storytelling
    `,
    image: "/images/services/ghostwriting.jpg",
  },
  {
    id: "videogames",
    title: "Custom Videogames",
    shortDescription: "Tailor-made 2D games for fun and branding.",
    longDescription: `
      Gamification meets branding: we build customized 2D games that
      entertain, educate, and promote engagement.

      Examples:
      - Branded mini-games
      - Gamified learning tools
      - NFT-integrated experiences
    `,
    image: "/images/services/videogames.jpg",
  },
  {
    id: "songs",
    title: "Custom Songs",
    shortDescription: "Personalized songs and soundtracks.",
    longDescription: `
      Music composition tailored to your project or brand.
      From jingles to full tracks, we deliver unique audio identity.

      Services:
      - Original soundtracks
      - Commercial jingles
      - Community anthems
    `,
    image: "/images/services/songs.jpg",
  },
  {
    id: "videos",
    title: "Animated Videos",
    shortDescription: "Customizable videos for campaigns and branding.",
    longDescription: `
      Fully animated videos that bring your message to life.
      Perfect for explaining, entertaining, or advertising.

      Types:
      - Explainer videos
      - Brand animations
      - Storytelling clips
    `,
    image: "/images/services/videos.jpg",
  },
  {
    id: "stickers",
    title: "Custom Stickers",
    shortDescription: "Digital stickers for chats, apps, and branding.",
    longDescription: `
      Branded and fun stickers designed for community engagement,
      platforms, and campaigns.

      Uses:
      - Telegram/Discord packs
      - Branded emojis
      - Collectible NFT-stickers
    `,
    image: "/images/services/stickers.png",
  },
];